# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LosTrouvee' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LosTrouvee
pod 'RealmSwift'
pod 'Firebase/Core'
pod 'Firebase/Auth'
  target 'LosTrouveeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LosTrouveeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
